### ISSUE TITLE
How to serialize into json or dict?

### ISSUE THREAD

**Issue by somkeo** [googleapis/python-containeranalysis#52]
Hi There,

I've been using this for a few months and it works great to grab occurrences and notes. On a previous version of the client the object being returned was serializable using google.protobuf.json_format.MessageToJson. On the current client, it now returns an Occurrence object.

Is there a serializer for object or would I have to manually build the dict?

<class 'grafeas.grafeas_v1.types.grafeas.Occurrence'>

**Comment by dinagraves** [comment]
Great question!   If you look at the [code](https://googleapis.dev/python/grafeas/latest/_modules/grafeas/grafeas_v1/types/grafeas.html#Occurrence) for the the grafeas Occurrence class, you can see that it is a protobuf message at its base.   This means, we can use all the protobuf functions on it!  

If you run `print(dir(note))` you can see all of the methods that object has.  The _pb method represents the note as the protobuf message.   Knowing this, we can then import the `google.protobuf` module to run the json_format function on it.  eg:

```
from grafeas.grafeas_v1 import Version
from google.cloud.devtools import containeranalysis_v1
from google.protobuf import json_format

#
# Your code here, where you are extracting the note
# 

print(json_format.MessageToJson(note._pb))
```
